// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvfmhbhxffgqftfogayr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2Zm1oYmh4ZmZncWZ0Zm9nYXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTQyODIsImV4cCI6MjA3MjQ5MDI4Mn0.xDHH6Da7TwoPk4L2-o3fIbL4ItIJnOdr-jUMwRuRPVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});